from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1289, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Load_button = QtWidgets.QPushButton(self.centralwidget)
        self.Load_button.setGeometry(QtCore.QRect(170, 460, 191, 41))
        self.Load_button.setObjectName("Load_button")
        self.origin_image = QtWidgets.QGraphicsView(self.centralwidget)
        self.origin_image.setGeometry(QtCore.QRect(80, 80, 381, 361))
        self.origin_image.setObjectName("origin_image")
        self.feature_image = QtWidgets.QGraphicsView(self.centralwidget)
        self.feature_image.setGeometry(QtCore.QRect(520, 80, 381, 361))
        self.feature_image.setObjectName("feature_image")
        self.Show_button = QtWidgets.QPushButton(self.centralwidget)
        self.Show_button.setGeometry(QtCore.QRect(620, 460, 191, 41))
        self.Show_button.setObjectName("Show_button")
        self.P_score = QtWidgets.QLabel(self.centralwidget)
        self.P_score.setGeometry(QtCore.QRect(960, 230, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.P_score.setFont(font)
        self.P_score.setObjectName("P_score")
        self.T_score = QtWidgets.QLabel(self.centralwidget)
        self.T_score.setGeometry(QtCore.QRect(960, 300, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.T_score.setFont(font)
        self.T_score.setObjectName("T_score")
        self.show_P_score = QtWidgets.QLabel(self.centralwidget)
        self.show_P_score.setGeometry(QtCore.QRect(1170, 220, 58, 51))
        self.show_P_score.setText("")
        self.show_P_score.setObjectName("show_P_score")
        self.show_T_score = QtWidgets.QLabel(self.centralwidget)
        self.show_T_score.setGeometry(QtCore.QRect(1140, 290, 58, 51))
        self.show_T_score.setText("")
        self.show_T_score.setObjectName("show_T_score")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Load_button.setText(_translate("MainWindow", "Load Image"))
        self.Show_button.setText(_translate("MainWindow", "Show Feature"))
        self.P_score.setText(_translate("MainWindow", "Predict Score："))
        self.T_score.setText(_translate("MainWindow", "True Score："))
